<?php
$_code = $this->getMethodCode();
$carrier = $this->getMethodInstance();
$_rate = $this->getRate();
$intervals = $this->getBudbeeIntervals();
?>
<?php if (count($intervals) ) : ?>
<ul class="form-list" id="shipping_form_<?php echo $_rate->getCode() ?>"> <!--style="display:none;"-->
    <li>
        <label for="budbee_delivery_date" ><?php echo $this->__('Select Time') ?></label>
        <span class="input-box">
            <select name="budbee_delivery_date">
                <?php foreach ($intervals as $key => $interval) :
                    $value = strtotime($interval->delivery->start->format('Y-m-d H:i')). ":"
                            .strtotime($interval->delivery->stop->format('Y-m-d H:i')). ":"
                            .strtotime($interval->collection->start->format('Y-m-d H:i')). ":"
                            .strtotime($interval->collection->stop->format('Y-m-d H:i'));
                    $label = $interval->delivery->start->format('j D H:i'). " - ". $interval->delivery->stop->format('H:i');
                ?>
                <option value='<?php echo $value?>'><?php echo $this->__($label);?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <label for="budbee_door_code"> <?php echo $this->__("Door Code") ?></label>
        <span class="input-box">
            <input type='text' name='budbee_door_code' id="<?php echo $_code ?>_door_code'" class='input-text' value='' />
        </span>
        <label for="budbee_outside_door"> <?php echo $this->__("Outside Door") ?></label>
        <span class="input-box">
             <select  name="budbee_outside_door">
                 <option value='0'><?php echo $this->__('No');?></option>
                 <option value='1'><?php echo $this->__('Yes');?></option>
             </select>
        </span>
        <label for="budbee_additional_info"> <?php echo $this->__("Additional information") ?></label>
        <span class="input-box">
            <textarea name="budbee_additional_info" ></textarea>
        </span>
    </li>
</ul>
<?php endif; ?>


<script type="text/javascript">
  /*  //<![CDATA[

    //]]>*/
</script>